{
  "openapi": "3.0.0",
  "info":
    {
      "title": "Mandus RESTful API",
      "description": "API-dokumentation med Swagger",
      "version": "1.0.0",
    },
  "servers":
    [
      {
        "description": "SwaggerHub API Auto Mocking",
        "url": "https://virtserver.swaggerhub.com/fjsx24-fcc/test-onsdag-user-api/1.0.0",
      },
      { "url": "http://localhost:8000", "description": "Local dev server" },
    ],
  "paths":
    {
      "/api/users":
        {
          "get":
            {
              "tags": ["users"],
              "summary": "Hämta alla användare",
              "description": "Returnerar en lista med alla användare",
              "responses":
                {
                  "200":
                    {
                      "description": "Lyckad hämtning av alla användare",
                      "content":
                        {
                          "application/json":
                            {
                              "schema":
                                {
                                  "type": "array",
                                  "items":
                                    { "$ref": "#/components/schemas/User" },
                                },
                              "examples":
                                {
                                  "mock-server":
                                    {
                                      "summary": "Exempel från SwaggerHub",
                                      "value":
                                        [
                                          { "id": 1, "name": "Kajsa" },
                                          { "id": 2, "name": "Erik" },
                                        ],
                                    },
                                  "local-server":
                                    {
                                      "summary": "Exempel från lokal utveckling",
                                      "value":
                                        [
                                          { "id": 1, "name": "Mandus" },
                                          { "id": 2, "name": "Hubert" },
                                        ],
                                    },
                                },
                            },
                        },
                    },
                },
            },
          "post":
            {
              "tags": ["users"],
              "summary": "Skapa en ny användare",
              "description": "Skapar en ny användare",
              "requestBody":
                {
                  "required": true,
                  "content":
                    {
                      "application/json":
                        { "schema": { "$ref": "#/components/schemas/User" } },
                    },
                },
              "responses":
                {
                  "201":
                    {
                      "description": "Användare skapad",
                      "content":
                        {
                          "application/json":
                            {
                              "schema":
                                { "$ref": "#/components/schemas/UserResponse" },
                            },
                        },
                    },
                },
            },
        },
    },
  "components":
    {
      "schemas":
        {
          "User":
            {
              "type": "object",
              "properties":
                {
                  "id":
                    {
                      "type": "integer",
                      "description": "Användarens unika id",
                      "example": 1,
                    },
                  "name":
                    {
                      "type": "string",
                      "description": "Användarens namn",
                      "example": "Exempelanvändare",
                    },
                },
            },
          "UserResponse":
            {
              "type": "object",
              "properties":
                {
                  "message":
                    {
                      "type": "string",
                      "description": "Bekräftelsemeddelande",
                    },
                  "user": { "$ref": "#/components/schemas/User" },
                },
            },
        },
    },
  "tags": [],
}
