openapi: 3.0.0
info:
  title: RESTful API
  description: API-dokumentation med Swagger
  version: 1.0.0

  servers:
    - url: https://virtserver.swaggerhub.com/fjsx24-fcc/my-exported-api/1.0.0
      description: Mock Server (auto-genererad av SwaggerHub)

paths:
  /api/users:
    get:
      tags:
        - users
      summary: Hämta alla användare
      description: Returnerar en lista med alla användare
      responses:
        "200":
          description: Lyckad hämtning av användare
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Användarens unika ID
                    name:
                      type: string
                      description: Användarens namn
    post:
      tags:
        - users
      summary: Skapa en ny användare
      description: Skapar en användare med ett namn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Namnet på användaren
                  example: Kristina
      responses:
        "201":
          description: Användare skapad
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Bekräftelsemeddelande
                  user:
                    type: object
                    description: Den skapade användaren
components: {}
tags: []
